#!/usr/bin/env python3
"""Train a custom "Hey Orio" openWakeWord model — runs OFF-DEVICE.

This is the `wakeword-training/` monorepo component, kept entirely separate from
the robot package (`orio-jetson/`) so PyTorch never touches the on-device
install. openWakeWord ships no "Orio" keyword, so the `oww` wake engine
(`orio-jetson/orio/wake_oww.py`) can only smoke-test with a built-in word until
we mint our own. This script drives openWakeWord's official training pipeline to
produce `hey_orio.onnx`, which then runs on the robot under the torch-free
onnxruntime path — i.e. **train heavy here, run lean on-device.**

⚠️  Do NOT run this in the robot's `uv` venv. openWakeWord training pulls in
**PyTorch**, which we deliberately keep out of the on-device install (the Jetson
GPU is reserved for the LLM + object detector). Run it on a separate powerful
machine (laptop / GPU box) in this folder's own environment:

    cd wakeword-training
    python -m venv .venv && source .venv/bin/activate
    pip install -r requirements.txt
    git clone https://github.com/rhasspy/piper-sample-generator  # synthetic positives

    python -m venv ~/oww-train && source ~/oww-train/bin/activate
    pip install "openwakeword" torch torchaudio torchinfo speechbrain \
        audiomentations acoustics mutagen pyyaml datasets scipy tqdm
    git clone https://github.com/rhasspy/piper-sample-generator  # synthetic positives

You also need negative/background data the trainer mixes in (download once):
  - Background audio   (e.g. an ACAV100M / FMA subset)            → --background
  - Room impulse resps (e.g. the MIT RIR survey)                  → --rir
  - Precomputed negative features + a false-positive validation set,
    both published by openWakeWord on Hugging Face                → edit the YAML
See the openWakeWord "automatic model training" docs for the exact archives.

Pipeline (three phases, run in order — re-runnable, they skip finished work):

    # 1) write a starter config you then review/fill in with dataset paths
    python train_orio_wakeword.py --write-config

    # 2) run the phases (generate synthetic clips → augment → train + export)
    python train_orio_wakeword.py --generate --augment --train

The trained `<model_name>.onnx` lands in the config's `output_dir`. Copy it onto
the robot at `orio-jetson/models/hey_orio.onnx` (it's committed there, so a clone
carries it), then launch the robot with:

    ORIO_WAKE_ENGINE=oww ORIO_WAKE_OWW_MODEL=models/hey_orio.onnx uv run main.py
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# Annotated starter config. We emit YAML as a template (not yaml.dump) so every
# field carries a comment — the dataset paths in particular MUST be filled in by
# hand before training. Values are openWakeWord's recommended starting points;
# revisit against the current training docs. `{...}` slots are filled below.
CONFIG_TEMPLATE = """\
# openWakeWord training config for Orio's wake word — generated by
# wakeword-training/train_orio_wakeword.py. Review every path before training.

# ── What to train ────────────────────────────────────────────────────────────
target_phrase: [{phrase!r}]   # the wake phrase(s); add mishearings as extra items
model_name: {model_name}      # output model basename → {model_name}.onnx
output_dir: {out_dir}         # where clips, features, and the model are written

# ── Synthetic positive generation (piper-sample-generator) ───────────────────
piper_sample_generator_path: {piper}   # local clone of rhasspy/piper-sample-generator
n_samples: 30000          # positive training clips to synthesize (more = better)
n_samples_val: 2000       # positive validation clips
tts_batch_size: 50        # lower if the TTS step runs out of GPU/CPU memory
custom_negative_phrases: []   # optional extra "sounds like the wake word" negatives

# ── Augmentation: mix clips with noise + room acoustics ──────────────────────
# Fill these with directories of audio you've downloaded (see the module header).
background_paths: []                  # dirs of background/noise audio
background_paths_duplication_rate: [1]
rir_paths: []                         # dirs of room-impulse-response WAVs
augmentation_rounds: 1
augmentation_batch_size: 16
total_length: 32000   # samples per clip; the augment phase auto-tunes this (>=2s)

# ── Negatives + validation (precomputed openWakeWord features, from HF) ──────
# Map a name → .npy of precomputed features for large negative corpora, and a
# held-out set to measure false positives. Download per the openWakeWord docs.
feature_data_files: {{}}                       # e.g. {{"ACAV100M": "feats.npy"}}
false_positive_validation_data_path: ""        # .npy of FP validation features

# ── Model + training ─────────────────────────────────────────────────────────
model_type: dnn          # "dnn" (default) or "rnn"
layer_size: 32           # hidden layer width
steps: 50000             # training steps
batch_n_per_class: {{"positive": 50, "adversarial_negative": 50}}
max_negative_weight: 1500
target_false_positives_per_hour: 0.2
"""


def write_config(path: Path, phrase: str, model_name: str, out_dir: str, piper: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        CONFIG_TEMPLATE.format(
            phrase=phrase, model_name=model_name, out_dir=out_dir, piper=piper
        )
    )
    print(f"✓ wrote starter config → {path}")
    print("  Edit it (dataset paths!) before running --generate/--augment/--train.")


def preflight() -> None:
    """Fail early with actionable guidance if the training env isn't set up."""
    missing = []
    try:
        import torch  # noqa: F401
    except ImportError:
        missing.append("torch (PyTorch)")
    try:
        import yaml  # noqa: F401
    except ImportError:
        missing.append("pyyaml")
    try:
        import openwakeword.train  # noqa: F401  (this import itself needs torch)
    except ImportError as exc:
        missing.append(f"openwakeword training deps ({exc})")
    if missing:
        sys.exit(
            "✗ Training environment is incomplete — missing: "
            + ", ".join(missing)
            + "\n  This tool runs OFF-DEVICE, not in the robot venv (see the file "
            "header for the full setup)."
        )


def run_phase(config: Path, *, generate: bool, augment: bool, train: bool) -> None:
    """Invoke openWakeWord's trainer for the requested phases, in order.

    Shells out to `python -m openwakeword.train` using the *current* interpreter
    (so it uses this training env's torch), one phase per call as the trainer
    expects. Each phase is re-runnable and skips work that's already done.
    """
    base = [sys.executable, "-m", "openwakeword.train", "--training_config", str(config)]
    phases = [
        ("--generate_clips", generate, "generating synthetic clips"),
        ("--augment_clips", augment, "augmenting + computing features"),
        ("--train_model", train, "training + exporting the model"),
    ]
    for flag, enabled, label in phases:
        if not enabled:
            continue
        print(f"\n▶ {label} …")
        result = subprocess.run([*base, flag])
        if result.returncode != 0:
            sys.exit(f"✗ phase {flag} failed (exit {result.returncode})")


def main() -> None:
    p = argparse.ArgumentParser(
        description="Train a custom 'Hey Orio' openWakeWord model (off-device).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--config", type=Path, default=Path("models/hey_orio.train.yaml"),
                   help="Training config YAML (written by --write-config).")
    p.add_argument("--phrase", default="hey orio", help="Wake phrase to train.")
    p.add_argument("--model-name", default="hey_orio", help="Output model basename.")
    p.add_argument("--out-dir", default="models/hey_orio",
                   help="Where clips/features/model are written.")
    p.add_argument("--piper", default="./piper-sample-generator",
                   help="Path to a piper-sample-generator clone.")
    p.add_argument("--write-config", action="store_true",
                   help="Write the starter config and exit (review before training).")
    p.add_argument("--generate", action="store_true", help="Phase 1: synthesize clips.")
    p.add_argument("--augment", action="store_true", help="Phase 2: augment + features.")
    p.add_argument("--train", action="store_true", help="Phase 3: train + export ONNX.")
    args = p.parse_args()

    # Write-config (or first run with no config) is the entry point; it needs no
    # torch, so users can scaffold on any machine before moving to the GPU box.
    if args.write_config or not args.config.exists():
        write_config(args.config, args.phrase, args.model_name, args.out_dir, args.piper)
        if args.write_config:
            return
        sys.exit("✗ Fill in the config above, then re-run with --generate/--augment/--train.")

    # Default to running the whole pipeline if no explicit phase was requested.
    generate, augment, train = args.generate, args.augment, args.train
    if not (generate or augment or train):
        generate = augment = train = True

    preflight()
    run_phase(args.config, generate=generate, augment=augment, train=train)
    print(
        f"\n✓ Done. Look for {args.model_name}.onnx in the config's output_dir.\n"
        f"  Copy it to the robot and run:\n"
        f"    ORIO_WAKE_ENGINE=oww ORIO_WAKE_OWW_MODEL=models/{args.model_name}.onnx uv run main.py"
    )


if __name__ == "__main__":
    main()
