[project]
name = "orio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elevenlabs>=2.60.0",
    "fastembed>=0.8.0",
    "langchain-anthropic>=0.3.0",
    "langchain-ollama>=1.1.0",
    "ollama>=0.6.2",
    "opencv-python>=5.0.0.93",
    "openwakeword>=0.6.0",
    "pygame>=2.6.1",
    "python-dotenv>=1.2.2",
    "sounddevice>=0.5.5",
    "sqlite-vec>=0.1.9",
    "ultralytics>=8.4.115",
]
